controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_annotations:
    resource:
        path: '@VkUserManagementBundle/Controller'
        namespace: App\Vk\UserManagement\Controller
    type: attribute
